### ISSUE TITLE
Virtualbox 6.0.x tracking

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#250]
This is a list of all the reasons to not use VirtualBox 6.0.x so far. Individual issues should not be opened unless there is a particular issue with our scripts, packer config, or Ansible playbooks.

- [x] Unable to create empty CD drive through GUI
- [ ] Apparent changes in how audio is configured (#249)
- [x] Odd error when importing an appliance (but then import seems to work)

We should start building for and using VirtualBox 6.0 when these issues are resolved. Additional issues that come up should be comment below and added to this comment.

**Comment by ripleymj** [comment]
CD drive resolved in master: https://www.virtualbox.org/ticket/18223
Import error resolved in master: https://www.virtualbox.org/ticket/18207
Debian saying 6.0 is post-Buster: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918968

**Comment by ripleymj** [comment]
Closing this in favor of #249
